---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: activityservice
spec:
  replicas: {{ .Values.chirper.activity_stream.replicas }}
  serviceName: activityservice
  template:
    metadata:
      labels:
        app: activityservice
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: "{{ .Release.Name }}"
        heritage: "{{ .Release.Service }}"        
    spec:
      containers:
      - env:
        - name: CASSANDRA_SERVICE_NAME
          value: "{{ .Values.chirper.cassandra.service }}"
        - name: "{{ .Values.chirper.activity_stream.secret }}"
          value: activityservice-application-secret
        - name: ACTIVITYSERVICE_BIND_PORT
          value: '9000'
        - name: ACTIVITYSERVICE_BIND_IP
          value: 0.0.0.0
        - name: AKKA_ACTOR_SYSTEM_NAME
          value: activityservice-v1
        - name: AKKA_REMOTING_BIND_PORT
          value: '2551'
        - name: AKKA_REMOTING_BIND_HOST
          value: $HOSTNAME.activityservice.{{ .Release.Namespace }}.svc.cluster.local
        - name: AKKA_SEED_NODES
          value: activityservice-0.activityservice.{{ .Release.Namespace }}.svc.cluster.local:2551,activityservice-1.activityservice.{{ .Release.Namespace }}.svc.cluster.local:2551,activityservice-2.activityservice.{{ .Release.Namespace }}.svc.cluster.local:2551
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: "{{ .Values.chirper.activity_stream.image.repo }}:{{ .Values.chirper.activity_stream.image.tag }}"
        imagePullPolicy: "{{ .Values.chirper.imagePullPolicy }}"
        name: activityservice
        ports:
        - containerPort: 9000
          name: http-lagom-api
        - containerPort: 2551
          name: akka-remote
        readinessProbe:
          httpGet:
            path: /_status/circuit-breaker/current
            port: 9000
          initialDelaySeconds: 5
          periodSeconds: 5
