---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: friendservice
spec:
  replicas: {{ .Values.chirper.friend.replicas }}
  serviceName: friendservice
  template:
    metadata:
      labels:
        app: friendservice
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: "{{ .Release.Name }}"
        heritage: "{{ .Release.Service }}"        
    spec:
      containers:
      - env:
        - name: CASSANDRA_SERVICE_NAME
          value: "{{ .Values.chirper.cassandra.service }}"
        - name: APPLICATION_SECRET
          value: "{{ .Values.chirper.friend.secret }}"
        - name: FRIENDSERVICE_BIND_PORT
          value: '9000'
        - name: FRIENDSERVICE_BIND_IP
          value: 0.0.0.0
        - name: AKKA_ACTOR_SYSTEM_NAME
          value: friendservice-v1
        - name: AKKA_REMOTING_BIND_PORT
          value: '2551'
        - name: AKKA_REMOTING_BIND_HOST
          value: $HOSTNAME.friendservice.{{ .Release.Namespace }}.svc.cluster.local
        - name: AKKA_SEED_NODES
          value: friendservice-0.friendservice.{{ .Release.Namespace }}.svc.cluster.local:2551,friendservice-1.friendservice.{{ .Release.Namespace }}.svc.cluster.local:2551,friendservice-2.friendservice.{{ .Release.Namespace }}.svc.cluster.local:2551
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: "{{ .Values.chirper.friend.image.repo }}:{{ .Values.chirper.friend.image.tag }}"
        imagePullPolicy: "{{ .Values.chirper.imagePullPolicy }}"
        name: friendservice
        ports:
        - containerPort: 9000
          name: tcp-lagom-api
        - containerPort: 2551
          name: akka-remote
        readinessProbe:
          httpGet:
            path: /_status/circuit-breaker/current
            port: 9000
          initialDelaySeconds: 5
          periodSeconds: 5
