chirper:
  cassandra:
    service: _cql._tcp.chirper-cassandra.default.svc.cluster.local
  ingress:
    host: ~
    tls:
      secret: ~
  imagePullPolicy: IfNotPresent

  activity_stream:
    replicas: 1
    secret: SECRET
    image:
      repo: chirper/activity-stream-impl
      tag: 1.0-SNAPSHOT

  chirp:
    replicas: 1
    secret: SECRET
    image:
      repo: chirper/chirp-impl
      tag: 1.0-SNAPSHOT

  friend:
    replicas: 1
    secret: SECRET
    image:
      repo: chirper/friend-impl
      tag: 1.0-SNAPSHOT

  front_end:
    replicas: 1
    image:
      repo: chirper/front-end
      tag: 1.0-SNAPSHOT

  nginx:
    backend:
      replicas: 1
      image:
        repo: gcr.io/google_containers/defaultbackend
        tag: "1.0"

    ingress:
      replicas: 1
      type: LoadBalancer
      image:
        repo: gcr.io/google_containers/nginx-ingress-controller
        tag: "0.9.0-beta.10"

cassandra:
  image:
    repo: gcr.io/google-samples/cassandra
    tag: v12
  config:
    max_heap_size: 512M
    heap_new_size: 100M
  persistence:
    enabled: false
  resources:
    requests:
      memory: 1Gi
      cpu: 250m
    limits:
      memory: 1Gi
      cpu: 250m